
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Murad
 */
public class reg extends javax.swing.JFrame {

    /**
     * Creates new form reg
     * 
     * 
     */
    
   String gender;
    public reg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        UAge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        UPass = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        UPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        UEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ULName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        UFName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        UAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(UAge);
        UAge.setBounds(190, 460, 90, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Age");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 460, 34, 30);

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 640, 130, 40);

        UPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(UPass);
        UPass.setBounds(190, 580, 330, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Password");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 570, 100, 22);

        UPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(UPhone);
        UPhone.setBounds(190, 510, 330, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Phone no.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 510, 100, 22);

        buttonGroup1.add(jRadioButtonFemale);
        jRadioButtonFemale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButtonFemale.setText("Female");
        jPanel1.add(jRadioButtonFemale);
        jRadioButtonFemale.setBounds(330, 400, 110, 30);

        buttonGroup1.add(jRadioButtonMale);
        jRadioButtonMale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButtonMale.setText("Male");
        jPanel1.add(jRadioButtonMale);
        jRadioButtonMale.setBounds(190, 400, 107, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 400, 70, 20);

        UEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(UEmail);
        UEmail.setBounds(190, 340, 320, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Email");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 330, 60, 22);

        UAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(UAddress);
        UAddress.setBounds(190, 240, 320, 70);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 240, 80, 22);

        ULName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(ULName);
        ULName.setBounds(190, 190, 320, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Last Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 190, 110, 20);

        UFName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UFNameActionPerformed(evt);
            }
        });
        jPanel1.add(UFName);
        UFName.setBounds(190, 140, 320, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 140, 100, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Registration as User");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 70, 450, 40);

        jPanel3.setBackground(new java.awt.Color(204, 255, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MultiSolve");

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 647, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 900, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/3IzejQ.jpg"))); // NOI18N
        jLabel1.setText(" ");
        jLabel1.setMaximumSize(new java.awt.Dimension(1300, 700));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 900, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UFNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
    
    Userlogin ul = new Userlogin();
    ul.setVisible(true);
    dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

       try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             String url="jdbc:sqlserver://localhost:1433;databaseName=MultiSolve;user=siam;password=123456;";
             Connection con = DriverManager.getConnection(url);
             String qurey = "Insert into UserData(Fname,Lname,Address,Email,Gender,Age,Phone,Password) Values (?,?,?,?,?,?,?,? )";
             PreparedStatement pst = con.prepareStatement(qurey);
             pst.setString(1, UFName.getText());
             pst.setString(2, ULName.getText());
             pst.setString(3, UAddress.getText());
             pst.setString(4, UEmail.getText());
             if(jRadioButtonMale.isSelected()){
               gender= "Male";
             }
             if(jRadioButtonFemale.isSelected()){
               gender= "Female";
             }
             pst.setString(5, gender);
             pst.setString(6, UAge.getText());
             pst.setString(7, UPhone.getText());
             pst.setString(8, UPass.getText());
               
             pst.executeUpdate();
          
             JOptionPane.showMessageDialog(null, "Registration Sucessfully!");          
            
       }
       catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UAddress;
    private javax.swing.JTextField UAge;
    private javax.swing.JTextField UEmail;
    private javax.swing.JTextField UFName;
    private javax.swing.JTextField ULName;
    private javax.swing.JTextField UPass;
    private javax.swing.JTextField UPhone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    // End of variables declaration//GEN-END:variables
}
